name: trending_git_repos_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  dio: ^5.7.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  connectivity_plus: 5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/lottie/retry_animation.json
